modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/German-Immersive-Railroading-Community/GIRC-Redstone/issues"

[[mods]]
modId="gircredstone"
version="${file.jarVersion}"
displayName="GIRC Redstone"
displayURL="https://girc.eu/"
authors="MrTroble, Jeronimo"
description='''
The official Wireless Redstone Mod for GIR.

Works in unloaded Chunks TM.
'''

[[dependencies.gircredstone]]
    modId="forge" 
    mandatory=true 
    versionRange="[25,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.gircredstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"